name: flutter_statusbarcolor
description: A package can help you to change your flutter app's statusbar's color or navigationbar's color programmatically.
version: 0.2.3
author: "fuyumi <fnatic.roach@gmail.com>"
homepage: https://github.com/mchome/flutter_statusbarcolor

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.fuyumi.flutterstatusbarcolor.flutterstatusbarcolor
    pluginClass: FlutterStatusbarcolorPlugin
